//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDay.Helpers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingDay.Helpers.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять.
        /// </summary>
        internal static string AcceptString {
            get {
                return ResourceManager.GetString("AcceptString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлено.
        /// </summary>
        internal static string AddedString {
            get {
                return ResourceManager.GetString("AddedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление тренировки.
        /// </summary>
        internal static string AddTrainingString {
            get {
                return ResourceManager.GetString("AddTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать упражнения.
        /// </summary>
        internal static string ChouseExerciseString {
            get {
                return ResourceManager.GetString("ChouseExerciseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите период:.
        /// </summary>
        internal static string ChousePeriodString {
            get {
                return ResourceManager.GetString("ChousePeriodString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во подходов: {0}.
        /// </summary>
        internal static string CountOfApprochesString {
            get {
                return ResourceManager.GetString("CountOfApprochesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во раз: {0}.
        /// </summary>
        internal static string CountOfTimesString {
            get {
                return ResourceManager.GetString("CountOfTimesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время: {0}.
        /// </summary>
        internal static string CurrentTimeString {
            get {
                return ResourceManager.GetString("CurrentTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалено.
        /// </summary>
        internal static string DeletedString {
            get {
                return ResourceManager.GetString("DeletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потраченное время: {0}.
        /// </summary>
        internal static string ElapsedTimeString {
            get {
                return ResourceManager.GetString("ElapsedTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые поля. Введите данные во все поля.
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текущий вес:.
        /// </summary>
        internal static string EnterCurrentWeightString {
            get {
                return ResourceManager.GetString("EnterCurrentWeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о упражнении.
        /// </summary>
        internal static string ExerciseInformationString {
            get {
                return ResourceManager.GetString("ExerciseInformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упражнения.
        /// </summary>
        internal static string ExercisesString {
            get {
                return ResourceManager.GetString("ExercisesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по мускулам.
        /// </summary>
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        internal static string FinishString {
            get {
                return ResourceManager.GetString("FinishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полгода.
        /// </summary>
        internal static string HalfYearString {
            get {
                return ResourceManager.GetString("HalfYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История тренировок.
        /// </summary>
        internal static string HistoryTrainings {
            get {
                return ResourceManager.GetString("HistoryTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   кг  .
        /// </summary>
        internal static string KilogramsString {
            get {
                return ResourceManager.GetString("KilogramsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пройденные тренировки.
        /// </summary>
        internal static string LastTrainingsString {
            get {
                return ResourceManager.GetString("LastTrainingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить тренеровку.
        /// </summary>
        internal static string MakeTrainingString {
            get {
                return ResourceManager.GetString("MakeTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мышцы.
        /// </summary>
        internal static string MusclesString {
            get {
                return ResourceManager.GetString("MusclesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название: {0}.
        /// </summary>
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        internal static string NameString1 {
            get {
                return ResourceManager.GetString("NameString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет тренеровок. Добавьте тренеровку..
        /// </summary>
        internal static string NoTrainingsNeedAddNewString {
            get {
                return ResourceManager.GetString("NoTrainingsNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сохранено.
        /// </summary>
        internal static string NotSavedString {
            get {
                return ResourceManager.GetString("NotSavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        internal static string OneMounthString {
            get {
                return ResourceManager.GetString("OneMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранено.
        /// </summary>
        internal static string SavedString {
            get {
                return ResourceManager.GetString("SavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание: {0}.
        /// </summary>
        internal static string ShortDescriptionString {
            get {
                return ResourceManager.GetString("ShortDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание:.
        /// </summary>
        internal static string ShortDescriptionString1 {
            get {
                return ResourceManager.GetString("ShortDescriptionString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 месяца.
        /// </summary>
        internal static string ThreeMounthString {
            get {
                return ResourceManager.GetString("ThreeMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание тренировки:.
        /// </summary>
        internal static string TrainingDescriptionString {
            get {
                return ResourceManager.GetString("TrainingDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упражнение завершено.
        /// </summary>
        internal static string TrainingFinishedString {
            get {
                return ResourceManager.GetString("TrainingFinishedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название тренировки:.
        /// </summary>
        internal static string TrainingNameString {
            get {
                return ResourceManager.GetString("TrainingNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировки.
        /// </summary>
        internal static string TrainingsBaseString {
            get {
                return ResourceManager.GetString("TrainingsBaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировка.
        /// </summary>
        internal static string TrainingString {
            get {
                return ResourceManager.GetString("TrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 месяца.
        /// </summary>
        internal static string TwoMounthString {
            get {
                return ResourceManager.GetString("TwoMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 недели.
        /// </summary>
        internal static string TwoWeeksString {
            get {
                return ResourceManager.GetString("TwoWeeksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        internal static string WeekString {
            get {
                return ResourceManager.GetString("WeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес: {0}.
        /// </summary>
        internal static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль веса.
        /// </summary>
        internal static string WeightString {
            get {
                return ResourceManager.GetString("WeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        internal static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
    }
}
