//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDay.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TrainingDay.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AbdominalString {
            get {
                return ResourceManager.GetString("AbdominalString", resourceCulture);
            }
        }
        
        internal static string AddedString {
            get {
                return ResourceManager.GetString("AddedString", resourceCulture);
            }
        }
        
        internal static string AddTrainingString {
            get {
                return ResourceManager.GetString("AddTrainingString", resourceCulture);
            }
        }
        
        internal static string AdviceAfterTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceAfterTrainingMessage", resourceCulture);
            }
        }
        
        internal static string AdviceBeforeTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceBeforeTrainingMessage", resourceCulture);
            }
        }
        
        internal static string AdviceString {
            get {
                return ResourceManager.GetString("AdviceString", resourceCulture);
            }
        }
        
        internal static string ArmsString {
            get {
                return ResourceManager.GetString("ArmsString", resourceCulture);
            }
        }
        
        internal static string BackString {
            get {
                return ResourceManager.GetString("BackString", resourceCulture);
            }
        }
        
        internal static string ChestString {
            get {
                return ResourceManager.GetString("ChestString", resourceCulture);
            }
        }
        
        internal static string ChouseExerciseString {
            get {
                return ResourceManager.GetString("ChouseExerciseString", resourceCulture);
            }
        }
        
        internal static string ChousePeriodString {
            get {
                return ResourceManager.GetString("ChousePeriodString", resourceCulture);
            }
        }
        
        internal static string CreateNewString {
            get {
                return ResourceManager.GetString("CreateNewString", resourceCulture);
            }
        }
        
        internal static string CurrentTimeString {
            get {
                return ResourceManager.GetString("CurrentTimeString", resourceCulture);
            }
        }
        
        internal static string DeletedString {
            get {
                return ResourceManager.GetString("DeletedString", resourceCulture);
            }
        }
        
        internal static string ElapsedTimeString {
            get {
                return ResourceManager.GetString("ElapsedTimeString", resourceCulture);
            }
        }
        
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        internal static string EnterCurrentWeightString {
            get {
                return ResourceManager.GetString("EnterCurrentWeightString", resourceCulture);
            }
        }
        
        internal static string EnterImageUrlString {
            get {
                return ResourceManager.GetString("EnterImageUrlString", resourceCulture);
            }
        }
        
        internal static string ExerciseInformationString {
            get {
                return ResourceManager.GetString("ExerciseInformationString", resourceCulture);
            }
        }
        
        internal static string ExercisesString {
            get {
                return ResourceManager.GetString("ExercisesString", resourceCulture);
            }
        }
        
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        internal static string FinishString {
            get {
                return ResourceManager.GetString("FinishString", resourceCulture);
            }
        }
        
        internal static string HalfYearString {
            get {
                return ResourceManager.GetString("HalfYearString", resourceCulture);
            }
        }
        
        internal static string HistoryTrainings {
            get {
                return ResourceManager.GetString("HistoryTrainings", resourceCulture);
            }
        }
        
        internal static string KilogramsString {
            get {
                return ResourceManager.GetString("KilogramsString", resourceCulture);
            }
        }
        
        internal static string LegsAndGlutesString {
            get {
                return ResourceManager.GetString("LegsAndGlutesString", resourceCulture);
            }
        }
        
        internal static string MakeTrainingString {
            get {
                return ResourceManager.GetString("MakeTrainingString", resourceCulture);
            }
        }
        
        internal static string MusclesString {
            get {
                return ResourceManager.GetString("MusclesString", resourceCulture);
            }
        }
        
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        internal static string NameString1 {
            get {
                return ResourceManager.GetString("NameString1", resourceCulture);
            }
        }
        
        internal static string NoExercisesNeedAddNewString {
            get {
                return ResourceManager.GetString("NoExercisesNeedAddNewString", resourceCulture);
            }
        }
        
        internal static string NoTrainingsNeedAddNewString {
            get {
                return ResourceManager.GetString("NoTrainingsNeedAddNewString", resourceCulture);
            }
        }
        
        internal static string NotSavedString {
            get {
                return ResourceManager.GetString("NotSavedString", resourceCulture);
            }
        }
        
        internal static string OneMounthString {
            get {
                return ResourceManager.GetString("OneMounthString", resourceCulture);
            }
        }
        
        internal static string RemoveSelectedString {
            get {
                return ResourceManager.GetString("RemoveSelectedString", resourceCulture);
            }
        }
        
        internal static string SavedString {
            get {
                return ResourceManager.GetString("SavedString", resourceCulture);
            }
        }
        
        internal static string SaveTrainingString {
            get {
                return ResourceManager.GetString("SaveTrainingString", resourceCulture);
            }
        }
        
        internal static string SearchByNameString {
            get {
                return ResourceManager.GetString("SearchByNameString", resourceCulture);
            }
        }
        
        internal static string ShortDescriptionString1 {
            get {
                return ResourceManager.GetString("ShortDescriptionString1", resourceCulture);
            }
        }
        
        internal static string ShouldersString {
            get {
                return ResourceManager.GetString("ShouldersString", resourceCulture);
            }
        }
        
        internal static string ThreeMounthString {
            get {
                return ResourceManager.GetString("ThreeMounthString", resourceCulture);
            }
        }
        
        internal static string TrainingDescriptionString {
            get {
                return ResourceManager.GetString("TrainingDescriptionString", resourceCulture);
            }
        }
        
        internal static string TrainingFinishedString {
            get {
                return ResourceManager.GetString("TrainingFinishedString", resourceCulture);
            }
        }
        
        internal static string TrainingNotifications {
            get {
                return ResourceManager.GetString("TrainingNotifications", resourceCulture);
            }
        }
        
        internal static string TrainingsBaseString {
            get {
                return ResourceManager.GetString("TrainingsBaseString", resourceCulture);
            }
        }
        
        internal static string TrainingString {
            get {
                return ResourceManager.GetString("TrainingString", resourceCulture);
            }
        }
        
        internal static string TwoMounthString {
            get {
                return ResourceManager.GetString("TwoMounthString", resourceCulture);
            }
        }
        
        internal static string TwoWeeksString {
            get {
                return ResourceManager.GetString("TwoWeeksString", resourceCulture);
            }
        }
        
        internal static string WeekString {
            get {
                return ResourceManager.GetString("WeekString", resourceCulture);
            }
        }
        
        internal static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        internal static string WeightString {
            get {
                return ResourceManager.GetString("WeightString", resourceCulture);
            }
        }
        
        internal static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
        
        internal static string BeginsAt {
            get {
                return ResourceManager.GetString("BeginsAt", resourceCulture);
            }
        }
        
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string OnTheseDays {
            get {
                return ResourceManager.GetString("OnTheseDays", resourceCulture);
            }
        }
        
        internal static string RepeatEvery {
            get {
                return ResourceManager.GetString("RepeatEvery", resourceCulture);
            }
        }
        
        internal static string SelectTraining {
            get {
                return ResourceManager.GetString("SelectTraining", resourceCulture);
            }
        }
        
        internal static string SetFrequency {
            get {
                return ResourceManager.GetString("SetFrequency", resourceCulture);
            }
        }
        
        internal static string NotAllFieldsEntered {
            get {
                return ResourceManager.GetString("NotAllFieldsEntered", resourceCulture);
            }
        }
        
        internal static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        internal static string GoalString {
            get {
                return ResourceManager.GetString("GoalString", resourceCulture);
            }
        }
        
        internal static string NoNotificationsString {
            get {
                return ResourceManager.GetString("NoNotificationsString", resourceCulture);
            }
        }
        
        internal static string SelectMusicText {
            get {
                return ResourceManager.GetString("SelectMusicText", resourceCulture);
            }
        }
        
        internal static string AreYouSerious {
            get {
                return ResourceManager.GetString("AreYouSerious", resourceCulture);
            }
        }
        
        internal static string DeleteExercises {
            get {
                return ResourceManager.GetString("DeleteExercises", resourceCulture);
            }
        }
        
        internal static string DayTextEveryDay {
            get {
                return ResourceManager.GetString("DayTextEveryDay", resourceCulture);
            }
        }
        
        internal static string DayTextFriday {
            get {
                return ResourceManager.GetString("DayTextFriday", resourceCulture);
            }
        }
        
        internal static string DayTextMonday {
            get {
                return ResourceManager.GetString("DayTextMonday", resourceCulture);
            }
        }
        
        internal static string DayTextSaturday {
            get {
                return ResourceManager.GetString("DayTextSaturday", resourceCulture);
            }
        }
        
        internal static string DayTextSunday {
            get {
                return ResourceManager.GetString("DayTextSunday", resourceCulture);
            }
        }
        
        internal static string DayTextThursday {
            get {
                return ResourceManager.GetString("DayTextThursday", resourceCulture);
            }
        }
        
        internal static string DayTextThusday {
            get {
                return ResourceManager.GetString("DayTextThusday", resourceCulture);
            }
        }
        
        internal static string DayTextWensdey {
            get {
                return ResourceManager.GetString("DayTextWensdey", resourceCulture);
            }
        }
        
        internal static string PleaseEnterYourNewWeight {
            get {
                return ResourceManager.GetString("PleaseEnterYourNewWeight", resourceCulture);
            }
        }
        
        internal static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        internal static string HelperString {
            get {
                return ResourceManager.GetString("HelperString", resourceCulture);
            }
        }
        
        internal static string NextString {
            get {
                return ResourceManager.GetString("NextString", resourceCulture);
            }
        }
        
        internal static string ShowAgainString {
            get {
                return ResourceManager.GetString("ShowAgainString", resourceCulture);
            }
        }
        
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        internal static string SelectMusclesString {
            get {
                return ResourceManager.GetString("SelectMusclesString", resourceCulture);
            }
        }
        
        internal static string MoreThanYearString {
            get {
                return ResourceManager.GetString("MoreThanYearString", resourceCulture);
            }
        }
        
        internal static string SettingsString {
            get {
                return ResourceManager.GetString("SettingsString", resourceCulture);
            }
        }
        
        internal static string LightThemeString {
            get {
                return ResourceManager.GetString("LightThemeString", resourceCulture);
            }
        }
        
        internal static string ChangesAcceptAfterReboot {
            get {
                return ResourceManager.GetString("ChangesAcceptAfterReboot", resourceCulture);
            }
        }
        
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        internal static string RepeatString {
            get {
                return ResourceManager.GetString("RepeatString", resourceCulture);
            }
        }
        
        internal static string CancelTrainingQuestion {
            get {
                return ResourceManager.GetString("CancelTrainingQuestion", resourceCulture);
            }
        }
        
        internal static string DayFreqString {
            get {
                return ResourceManager.GetString("DayFreqString", resourceCulture);
            }
        }
        
        internal static string WeightNotifyString {
            get {
                return ResourceManager.GetString("WeightNotifyString", resourceCulture);
            }
        }
        
        internal static string SuperSetString {
            get {
                return ResourceManager.GetString("SuperSetString", resourceCulture);
            }
        }
        
        internal static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        internal static string CopyString {
            get {
                return ResourceManager.GetString("CopyString", resourceCulture);
            }
        }
        
        internal static string MoveString {
            get {
                return ResourceManager.GetString("MoveString", resourceCulture);
            }
        }
        
        internal static string ExerciseString {
            get {
                return ResourceManager.GetString("ExerciseString", resourceCulture);
            }
        }
        
        internal static string HistoryString {
            get {
                return ResourceManager.GetString("HistoryString", resourceCulture);
            }
        }
        
        internal static string CopyExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("CopyExercisesFinishedMessage", resourceCulture);
            }
        }
        
        internal static string MoveExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("MoveExercisesFinishedMessage", resourceCulture);
            }
        }
        
        internal static string SuperSetCreatedMessage {
            get {
                return ResourceManager.GetString("SuperSetCreatedMessage", resourceCulture);
            }
        }
        
        internal static string ReturnToTrainingMessage {
            get {
                return ResourceManager.GetString("ReturnToTrainingMessage", resourceCulture);
            }
        }
        
        internal static string DeleteExerciseFromSuperSetQuestion {
            get {
                return ResourceManager.GetString("DeleteExerciseFromSuperSetQuestion", resourceCulture);
            }
        }
        
        internal static string ScreenOnWhenImplementing {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementing", resourceCulture);
            }
        }
        
        internal static string NoLastTrainings {
            get {
                return ResourceManager.GetString("NoLastTrainings", resourceCulture);
            }
        }
        
        internal static string RepsAndWeightString {
            get {
                return ResourceManager.GetString("RepsAndWeightString", resourceCulture);
            }
        }
        
        internal static string NoWeightHistory {
            get {
                return ResourceManager.GetString("NoWeightHistory", resourceCulture);
            }
        }
        
        internal static string ChooseTrainingOrNewString {
            get {
                return ResourceManager.GetString("ChooseTrainingOrNewString", resourceCulture);
            }
        }
        
        internal static string ContinueLastTrainingQuestion {
            get {
                return ResourceManager.GetString("ContinueLastTrainingQuestion", resourceCulture);
            }
        }
        
        internal static string CardioString {
            get {
                return ResourceManager.GetString("CardioString", resourceCulture);
            }
        }
        
        internal static string ShareTrainingString {
            get {
                return ResourceManager.GetString("ShareTrainingString", resourceCulture);
            }
        }
        
        internal static string RemoveString {
            get {
                return ResourceManager.GetString("RemoveString", resourceCulture);
            }
        }
        
        internal static string DistanceString {
            get {
                return ResourceManager.GetString("DistanceString", resourceCulture);
            }
        }
        
        internal static string TimeString {
            get {
                return ResourceManager.GetString("TimeString", resourceCulture);
            }
        }
        
        internal static string HourString {
            get {
                return ResourceManager.GetString("HourString", resourceCulture);
            }
        }
        
        internal static string MinuteString {
            get {
                return ResourceManager.GetString("MinuteString", resourceCulture);
            }
        }
        
        internal static string SecondString {
            get {
                return ResourceManager.GetString("SecondString", resourceCulture);
            }
        }
        
        internal static string ExerciseForTypeString {
            get {
                return ResourceManager.GetString("ExerciseForTypeString", resourceCulture);
            }
        }
        
        internal static string HomeString {
            get {
                return ResourceManager.GetString("HomeString", resourceCulture);
            }
        }
        
        internal static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        internal static string GroupingEnterNameofGroup {
            get {
                return ResourceManager.GetString("GroupingEnterNameofGroup", resourceCulture);
            }
        }
        
        internal static string GroupingTrainingInGroup {
            get {
                return ResourceManager.GetString("GroupingTrainingInGroup", resourceCulture);
            }
        }
        
        internal static string GroupingTrainingNotInGroup {
            get {
                return ResourceManager.GetString("GroupingTrainingNotInGroup", resourceCulture);
            }
        }
        
        internal static string SharedString {
            get {
                return ResourceManager.GetString("SharedString", resourceCulture);
            }
        }
        
        internal static string GroupingDefaultName {
            get {
                return ResourceManager.GetString("GroupingDefaultName", resourceCulture);
            }
        }
        
        internal static string ChooseGroupOrNewString {
            get {
                return ResourceManager.GetString("ChooseGroupOrNewString", resourceCulture);
            }
        }
        
        internal static string ScreenOnWhenImplementingTip {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementingTip", resourceCulture);
            }
        }
        
        internal static string WhatNewString {
            get {
                return ResourceManager.GetString("WhatNewString", resourceCulture);
            }
        }
        
        internal static string AuthorString {
            get {
                return ResourceManager.GetString("AuthorString", resourceCulture);
            }
        }
        
        internal static string MarkTheRequiredExercisesAndPress {
            get {
                return ResourceManager.GetString("MarkTheRequiredExercisesAndPress", resourceCulture);
            }
        }
        
        internal static string StartWorkoutString {
            get {
                return ResourceManager.GetString("StartWorkoutString", resourceCulture);
            }
        }
        
        internal static string WeightControlString {
            get {
                return ResourceManager.GetString("WeightControlString", resourceCulture);
            }
        }
        
        internal static string SkipString {
            get {
                return ResourceManager.GetString("SkipString", resourceCulture);
            }
        }
        
        internal static string VideoString {
            get {
                return ResourceManager.GetString("VideoString", resourceCulture);
            }
        }
        
        internal static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        internal static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        internal static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        internal static string DeleteTraining {
            get {
                return ResourceManager.GetString("DeleteTraining", resourceCulture);
            }
        }
        
        internal static string HipsString {
            get {
                return ResourceManager.GetString("HipsString", resourceCulture);
            }
        }
        
        internal static string WaistString {
            get {
                return ResourceManager.GetString("WaistString", resourceCulture);
            }
        }
        
        internal static string WaistHipMessage {
            get {
                return ResourceManager.GetString("WaistHipMessage", resourceCulture);
            }
        }
        
        internal static string NewsString {
            get {
                return ResourceManager.GetString("NewsString", resourceCulture);
            }
        }
        
        internal static string FitnessString {
            get {
                return ResourceManager.GetString("FitnessString", resourceCulture);
            }
        }
        
        internal static string NoString {
            get {
                return ResourceManager.GetString("NoString", resourceCulture);
            }
        }
        
        internal static string YesString {
            get {
                return ResourceManager.GetString("YesString", resourceCulture);
            }
        }
        
        internal static string ShowToolTipsString {
            get {
                return ResourceManager.GetString("ShowToolTipsString", resourceCulture);
            }
        }
        
        internal static string AddTrainingButtonToolTip {
            get {
                return ResourceManager.GetString("AddTrainingButtonToolTip", resourceCulture);
            }
        }
    }
}
