//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingDay.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdominal.
        /// </summary>
        internal static string AbdominalString {
            get {
                return ResourceManager.GetString("AbdominalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string AddedString {
            get {
                return ResourceManager.GetString("AddedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workout.
        /// </summary>
        internal static string AddTrainingString {
            get {
                return ResourceManager.GetString("AddTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice and Tips.
        /// </summary>
        internal static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After workout, the post-workout routine is useful, the post-workout routine allows smoothing the transition from high-intensity work to a state of rest. You thereby reduce the burden on the heart muscle, which has to pump blood intensively, to remove its stagnation from the muscles and provide it with internal organs. Suitable: Easy running, smoothly turning into walking (you can in place). Easy work on a bicycle or elliptical simulator, a stepper with a smooth decrease in intensity up to a stop. Jumping on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdviceAfterTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceAfterTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretching before workout is a complex of exercises for preparing the body for physical activity, which will help you avoid injuries and conduct the session as efficiently as possible. Stretching speeds up metabolic processes. Stretching before exercise improves blood circulation, which will saturate your muscles with oxygen and nutrients. This will help improve endurance during class. The warmed muscles are better compressed and relax during workout, which means that your strengths will be higher during th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdviceBeforeTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceBeforeTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice.
        /// </summary>
        internal static string AdviceString {
            get {
                return ResourceManager.GetString("AdviceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you serious?.
        /// </summary>
        internal static string AreYouSerious {
            get {
                return ResourceManager.GetString("AreYouSerious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms.
        /// </summary>
        internal static string ArmsString {
            get {
                return ResourceManager.GetString("ArmsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: {0}.
        /// </summary>
        internal static string AuthorString {
            get {
                return ResourceManager.GetString("AuthorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackString {
            get {
                return ResourceManager.GetString("BackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins at.
        /// </summary>
        internal static string BeginsAt {
            get {
                return ResourceManager.GetString("BeginsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel workout?.
        /// </summary>
        internal static string CancelTrainingQuestion {
            get {
                return ResourceManager.GetString("CancelTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        internal static string CardioString {
            get {
                return ResourceManager.GetString("CardioString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be accepted after restart application.
        /// </summary>
        internal static string ChangesAcceptAfterReboot {
            get {
                return ResourceManager.GetString("ChangesAcceptAfterReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string ChestString {
            get {
                return ResourceManager.GetString("ChestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group or create a new one by pressing the button.
        /// </summary>
        internal static string ChooseGroupOrNewString {
            get {
                return ResourceManager.GetString("ChooseGroupOrNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a workout or Create new.
        /// </summary>
        internal static string ChooseTrainingOrNewString {
            get {
                return ResourceManager.GetString("ChooseTrainingOrNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chouse exercise.
        /// </summary>
        internal static string ChouseExerciseString {
            get {
                return ResourceManager.GetString("ChouseExerciseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chouse period:.
        /// </summary>
        internal static string ChousePeriodString {
            get {
                return ResourceManager.GetString("ChousePeriodString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with your last performing workout?.
        /// </summary>
        internal static string ContinueLastTrainingQuestion {
            get {
                return ResourceManager.GetString("ContinueLastTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coping workouts finished.
        /// </summary>
        internal static string CopyExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("CopyExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyString {
            get {
                return ResourceManager.GetString("CopyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string CreateNewString {
            get {
                return ResourceManager.GetString("CreateNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0}.
        /// </summary>
        internal static string CurrentTimeString {
            get {
                return ResourceManager.GetString("CurrentTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every (days).
        /// </summary>
        internal static string DayFreqString {
            get {
                return ResourceManager.GetString("DayFreqString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string DayTextEveryDay {
            get {
                return ResourceManager.GetString("DayTextEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string DayTextFriday {
            get {
                return ResourceManager.GetString("DayTextFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string DayTextMonday {
            get {
                return ResourceManager.GetString("DayTextMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string DayTextSaturday {
            get {
                return ResourceManager.GetString("DayTextSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string DayTextSunday {
            get {
                return ResourceManager.GetString("DayTextSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string DayTextThursday {
            get {
                return ResourceManager.GetString("DayTextThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string DayTextThusday {
            get {
                return ResourceManager.GetString("DayTextThusday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string DayTextWensdey {
            get {
                return ResourceManager.GetString("DayTextWensdey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string DeletedString {
            get {
                return ResourceManager.GetString("DeletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete exercise from superset?.
        /// </summary>
        internal static string DeleteExerciseFromSuperSetQuestion {
            get {
                return ResourceManager.GetString("DeleteExerciseFromSuperSetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Exercises.
        /// </summary>
        internal static string DeleteExercises {
            get {
                return ResourceManager.GetString("DeleteExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete training.
        /// </summary>
        internal static string DeleteTraining {
            get {
                return ResourceManager.GetString("DeleteTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        internal static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string DistanceString {
            get {
                return ResourceManager.GetString("DistanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time: {0:hh\:mm\:ss}.
        /// </summary>
        internal static string ElapsedTimeString {
            get {
                return ResourceManager.GetString("ElapsedTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields. All fields should be entered.
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter weight:.
        /// </summary>
        internal static string EnterCurrentWeightString {
            get {
                return ResourceManager.GetString("EnterCurrentWeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL for exercise`s image:.
        /// </summary>
        internal static string EnterImageUrlString {
            get {
                return ResourceManager.GetString("EnterImageUrlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        internal static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise for .
        /// </summary>
        internal static string ExerciseForTypeString {
            get {
                return ResourceManager.GetString("ExerciseForTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise information.
        /// </summary>
        internal static string ExerciseInformationString {
            get {
                return ResourceManager.GetString("ExerciseInformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string ExercisesString {
            get {
                return ResourceManager.GetString("ExercisesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        internal static string ExerciseString {
            get {
                return ResourceManager.GetString("ExerciseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle`s filter.
        /// </summary>
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishString {
            get {
                return ResourceManager.GetString("FinishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string FitnessString {
            get {
                return ResourceManager.GetString("FitnessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string GoalString {
            get {
                return ResourceManager.GetString("GoalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string GroupingDefaultName {
            get {
                return ResourceManager.GetString("GroupingDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter group`s name.
        /// </summary>
        internal static string GroupingEnterNameofGroup {
            get {
                return ResourceManager.GetString("GroupingEnterNameofGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout already in group.
        /// </summary>
        internal static string GroupingTrainingInGroup {
            get {
                return ResourceManager.GetString("GroupingTrainingInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout already in Default group.
        /// </summary>
        internal static string GroupingTrainingNotInGroup {
            get {
                return ResourceManager.GetString("GroupingTrainingNotInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half year.
        /// </summary>
        internal static string HalfYearString {
            get {
                return ResourceManager.GetString("HalfYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select exercises and checkmark selected exercises.
        /// </summary>
        internal static string HelpDeleteUnusefulExercises {
            get {
                return ResourceManager.GetString("HelpDeleteUnusefulExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELPER.
        /// </summary>
        internal static string HelperString {
            get {
                return ResourceManager.GetString("HelperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hips.
        /// </summary>
        internal static string HipsString {
            get {
                return ResourceManager.GetString("HipsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryString {
            get {
                return ResourceManager.GetString("HistoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed workouts.
        /// </summary>
        internal static string HistoryTrainings {
            get {
                return ResourceManager.GetString("HistoryTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Inventory.
        /// </summary>
        internal static string HomeString {
            get {
                return ResourceManager.GetString("HomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string HourString {
            get {
                return ResourceManager.GetString("HourString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kg .
        /// </summary>
        internal static string KilogramsString {
            get {
                return ResourceManager.GetString("KilogramsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs and Glutes.
        /// </summary>
        internal static string LegsAndGlutesString {
            get {
                return ResourceManager.GetString("LegsAndGlutesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string LightThemeString {
            get {
                return ResourceManager.GetString("LightThemeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string MakeTrainingString {
            get {
                return ResourceManager.GetString("MakeTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinuteString {
            get {
                return ResourceManager.GetString("MinuteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than year.
        /// </summary>
        internal static string MoreThanYearString {
            get {
                return ResourceManager.GetString("MoreThanYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving workouts finished.
        /// </summary>
        internal static string MoveExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("MoveExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveString {
            get {
                return ResourceManager.GetString("MoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Muscles.
        /// </summary>
        internal static string MusclesString {
            get {
                return ResourceManager.GetString("MusclesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameString1 {
            get {
                return ResourceManager.GetString("NameString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsString {
            get {
                return ResourceManager.GetString("NewsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextString {
            get {
                return ResourceManager.GetString("NextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exercises. You should add exercise..
        /// </summary>
        internal static string NoExercisesNeedAddNewString {
            get {
                return ResourceManager.GetString("NoExercisesNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workouts completed yet.
        /// </summary>
        internal static string NoLastTrainings {
            get {
                return ResourceManager.GetString("NoLastTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications. You should add notification..
        /// </summary>
        internal static string NoNotificationsString {
            get {
                return ResourceManager.GetString("NoNotificationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all fields entered.
        /// </summary>
        internal static string NotAllFieldsEntered {
            get {
                return ResourceManager.GetString("NotAllFieldsEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workouts. You should add workout..
        /// </summary>
        internal static string NoTrainingsNeedAddNewString {
            get {
                return ResourceManager.GetString("NoTrainingsNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not saved.
        /// </summary>
        internal static string NotSavedString {
            get {
                return ResourceManager.GetString("NotSavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered your weight.
        /// </summary>
        internal static string NoWeightHistory {
            get {
                return ResourceManager.GetString("NoWeightHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounth.
        /// </summary>
        internal static string OneMounthString {
            get {
                return ResourceManager.GetString("OneMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On These Days.
        /// </summary>
        internal static string OnTheseDays {
            get {
                return ResourceManager.GetString("OnTheseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new weight. Maybe something has changed..
        /// </summary>
        internal static string PleaseEnterYourNewWeight {
            get {
                return ResourceManager.GetString("PleaseEnterYourNewWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        internal static string RemoveSelectedString {
            get {
                return ResourceManager.GetString("RemoveSelectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveString {
            get {
                return ResourceManager.GetString("RemoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        internal static string RepeatEvery {
            get {
                return ResourceManager.GetString("RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string RepeatString {
            get {
                return ResourceManager.GetString("RepeatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions | Weight.
        /// </summary>
        internal static string RepsAndWeightString {
            get {
                return ResourceManager.GetString("RepsAndWeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not implemented a workout for a long time. Maybe today is that day?.
        /// </summary>
        internal static string ReturnToTrainingMessage {
            get {
                return ResourceManager.GetString("ReturnToTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SavedString {
            get {
                return ResourceManager.GetString("SavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveTrainingString {
            get {
                return ResourceManager.GetString("SaveTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen should be turned on when doing a workout.
        /// </summary>
        internal static string ScreenOnWhenImplementing {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable to save battery.
        /// </summary>
        internal static string ScreenOnWhenImplementingTip {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Name.
        /// </summary>
        internal static string SearchByNameString {
            get {
                return ResourceManager.GetString("SearchByNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string SecondString {
            get {
                return ResourceManager.GetString("SecondString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Muscles.
        /// </summary>
        internal static string SelectMusclesString {
            get {
                return ResourceManager.GetString("SelectMusclesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        internal static string SelectMusicText {
            get {
                return ResourceManager.GetString("SelectMusicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select workout.
        /// </summary>
        internal static string SelectTraining {
            get {
                return ResourceManager.GetString("SelectTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set frequency.
        /// </summary>
        internal static string SetFrequency {
            get {
                return ResourceManager.GetString("SetFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsString {
            get {
                return ResourceManager.GetString("SettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string SharedString {
            get {
                return ResourceManager.GetString("SharedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareString {
            get {
                return ResourceManager.GetString("ShareString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share workout.
        /// </summary>
        internal static string ShareTrainingString {
            get {
                return ResourceManager.GetString("ShareTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string ShortDescriptionString1 {
            get {
                return ResourceManager.GetString("ShortDescriptionString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        internal static string ShouldersString {
            get {
                return ResourceManager.GetString("ShouldersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show again.
        /// </summary>
        internal static string ShowAgainString {
            get {
                return ResourceManager.GetString("ShowAgainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string SkipString {
            get {
                return ResourceManager.GetString("SkipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Position.
        /// </summary>
        internal static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Workout.
        /// </summary>
        internal static string StartWorkoutString {
            get {
                return ResourceManager.GetString("StartWorkoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet created.
        /// </summary>
        internal static string SuperSetCreatedMessage {
            get {
                return ResourceManager.GetString("SuperSetCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet.
        /// </summary>
        internal static string SuperSetString {
            get {
                return ResourceManager.GetString("SuperSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 mounth.
        /// </summary>
        internal static string ThreeMounthString {
            get {
                return ResourceManager.GetString("ThreeMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TimeString {
            get {
                return ResourceManager.GetString("TimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout`s description:.
        /// </summary>
        internal static string TrainingDescriptionString {
            get {
                return ResourceManager.GetString("TrainingDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout finished.
        /// </summary>
        internal static string TrainingFinishedString {
            get {
                return ResourceManager.GetString("TrainingFinishedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string TrainingNotifications {
            get {
                return ResourceManager.GetString("TrainingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        internal static string TrainingsBaseString {
            get {
                return ResourceManager.GetString("TrainingsBaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string TrainingString {
            get {
                return ResourceManager.GetString("TrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 mounth.
        /// </summary>
        internal static string TwoMounthString {
            get {
                return ResourceManager.GetString("TwoMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 weeks.
        /// </summary>
        internal static string TwoWeeksString {
            get {
                return ResourceManager.GetString("TwoWeeksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string VideoString {
            get {
                return ResourceManager.GetString("VideoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist-Hip Index._Index value = {0}._Read more?.
        /// </summary>
        internal static string WaistHipMessage {
            get {
                return ResourceManager.GetString("WaistHipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string WaistString {
            get {
                return ResourceManager.GetString("WaistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string WeekString {
            get {
                return ResourceManager.GetString("WeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Control.
        /// </summary>
        internal static string WeightControlString {
            get {
                return ResourceManager.GetString("WeightControlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        internal static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight entry notifications.
        /// </summary>
        internal static string WeightNotifyString {
            get {
                return ResourceManager.GetString("WeightNotifyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WeightString {
            get {
                return ResourceManager.GetString("WeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATES.
        /// </summary>
        internal static string WhatNewString {
            get {
                return ResourceManager.GetString("WhatNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
    }
}
